 # Data Preprocessing

## Objectives

In this notebook, we will prepare the dataset for Artificial Neural Network (ANN) training by:

- Removing irrelevant features
- Encoding categorical variables
- Splitting the dataset into training and testing sets
- Scaling numerical features
- Preventing data leakage
- Preparing the final input for ANN

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/raw/Churn_Modelling.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
print(df.shape)

(10000, 14)

In [4]:
df.drop(
    columns=[
        "RowNumber",
        "CustomerId",
        "Surname"
    ],
    inplace=True
)

df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
X = df.drop("Exited", axis=1)

y = df["Exited"]

In [6]:
le = LabelEncoder()

X["Gender"] = le.fit_transform(X["Gender"])

In [7]:
X = pd.get_dummies(X,
    columns=["Geography"],
    drop_first=True,
    dtype=int
)

In [8]:
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,1

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [10]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [11]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (8000, 11)
X_test  : (2000, 11)
y_train : (8000,)
y_test  : (2000,)

In [12]:
print(np.mean(X_train, axis=0))
print(np.std(X_train, axis=0))

[-5.72875081e-16  7.10542736e-17  2.48689958e-16 -9.81437154e-17
  5.77315973e-17 -9.50350909e-17  4.44089210e-18  4.26325641e-17
 -6.69464484e-17  9.45910017e-17  7.77156117e-17]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [ ]:
# Convert scaled X_train and X_test NumPy arrays back to DataFrames for easier CSV saving
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

# Save the processed data to CSV files
X_train_df.to_csv("../data/processed/X_train_processed.csv", index=False)
X_test_df.to_csv("../data/processed/X_test_processed.csv", index=False)
y_train.to_csv("../data/processed/y_train_processed.csv", index=False)
y_test.to_csv("../data/processed/y_test_processed.csv", index=False)

print("Processed data saved successfully:")

Processed data saved successfully:
- X_train_processed.csv
- X_test_processed.csv
- y_train_processed.csv
- y_test_processed.csv

In [ ]:
import joblib

# Save scaler
joblib.dump(scaler, "../models/scaler.pkl")

# Save label encoder
joblib.dump(le, "../models/label_encoder.pkl")

print("✅ Scaler and Label Encoder saved successfully!")

✅ Scaler and Label Encoder saved successfully!